name: fieldawy_store
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  meta: ^1.15.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.5.1
  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  flutter_riverpod: ^2.5.1
  font_awesome_flutter: ^10.6.0
  go_router: ^16.1.0
  firebase_auth: ^6.0.0
  cloud_functions: ^6.0.0

  cached_network_image: ^3.3.1
  google_sign_in: ^6.2.1
  image_picker: ^1.1.2
  firebase_storage: ^13.0.0
  permission_handler: ^12.0.1
  url_launcher: ^6.3.0
  flutter_localizations:
    sdk: flutter
  cloudinary_public: ^0.23.1
  shared_preferences: ^2.5.3
  easy_localization: ^3.0.8
  package_info_plus: ^8.3.0
  flutter_zoom_drawer: ^3.2.0
  cloud_firestore: ^6.0.0
  path: ^1.9.1
  intl: ^0.20.2
  google_mlkit_text_recognition: ^0.11.0
  flutter_image_compress: ^2.3.0
  path_provider: ^2.1.5
  http: ^1.2.1
  crypto: ^3.0.6
  salomon_bottom_bar: ^3.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter_native_splash:
  
  color: "#f2fcff"
  image: assets/logo_light.png
  color_dark: "#1d232a"
  image_dark: assets/logo_dark.png

  android_12:
   
    color: "#f2fcff"
    image: assets/logo_light.png
    color_dark: "#1d232a"
    image_dark: assets/logo_dark.png

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/translations/

fonts:
  - family: Cairo
    fonts:
      - asset: assets/fonts/Cairo-Regular.ttf
      - asset: assets/fonts/Cairo-Bold.ttf
        weight: 700

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app_icon.png"
